export interface CurrencyInfo {
  /** ISO 4217 alphabetic code, e.g. "EUR". */
  code: string;
  /** Minor-unit exponent: JPY 0, EUR 2, KWD 3. */
  exponent: number;
  /** English name; UI may localize via Intl.DisplayNames. */
  name: string;
}

/**
 * Compact source table: [code, exponent, English name]. Exponents follow the
 * ISO 4217 list (not CLDR display digits, which differ for e.g. IQD/IRR/LAK).
 *
 * Excluded on purpose:
 * - precious metals (XAU, XAG, XPD, XPT), SDR/units of account (XDR, XSU, XUA, XB*),
 *   testing/no-currency codes (XTS, XXX);
 * - fund / index / same-day codes (BOV, CHE, CHW, CLF, COU, MXV, USN, UYI, UYW);
 * - withdrawn codes still known to CLDR: ANG (→ XCG, 2025), BGN (→ EUR, 2026),
 *   CUC, HRK (→ EUR, 2023), SLL (→ SLE), ZWL (→ ZWG), plus older MRO/STD/VEF/BYR.
 */
const TABLE: ReadonlyArray<readonly [string, number, string]> = [
  ["AED", 2, "UAE Dirham"],
  ["AFN", 2, "Afghani"],
  ["ALL", 2, "Lek"],
  ["AMD", 2, "Armenian Dram"],
  ["AOA", 2, "Kwanza"],
  ["ARS", 2, "Argentine Peso"],
  ["AUD", 2, "Australian Dollar"],
  ["AWG", 2, "Aruban Florin"],
  ["AZN", 2, "Azerbaijan Manat"],
  ["BAM", 2, "Convertible Mark"],
  ["BBD", 2, "Barbados Dollar"],
  ["BDT", 2, "Taka"],
  ["BHD", 3, "Bahraini Dinar"],
  ["BIF", 0, "Burundi Franc"],
  ["BMD", 2, "Bermudian Dollar"],
  ["BND", 2, "Brunei Dollar"],
  ["BOB", 2, "Boliviano"],
  ["BRL", 2, "Brazilian Real"],
  ["BSD", 2, "Bahamian Dollar"],
  ["BTN", 2, "Ngultrum"],
  ["BWP", 2, "Pula"],
  ["BYN", 2, "Belarusian Ruble"],
  ["BZD", 2, "Belize Dollar"],
  ["CAD", 2, "Canadian Dollar"],
  ["CDF", 2, "Congolese Franc"],
  ["CHF", 2, "Swiss Franc"],
  ["CLP", 0, "Chilean Peso"],
  ["CNY", 2, "Yuan Renminbi"],
  ["COP", 2, "Colombian Peso"],
  ["CRC", 2, "Costa Rican Colon"],
  ["CUP", 2, "Cuban Peso"],
  ["CVE", 2, "Cabo Verde Escudo"],
  ["CZK", 2, "Czech Koruna"],
  ["DJF", 0, "Djibouti Franc"],
  ["DKK", 2, "Danish Krone"],
  ["DOP", 2, "Dominican Peso"],
  ["DZD", 2, "Algerian Dinar"],
  ["EGP", 2, "Egyptian Pound"],
  ["ERN", 2, "Nakfa"],
  ["ETB", 2, "Ethiopian Birr"],
  ["EUR", 2, "Euro"],
  ["FJD", 2, "Fiji Dollar"],
  ["FKP", 2, "Falkland Islands Pound"],
  ["GBP", 2, "Pound Sterling"],
  ["GEL", 2, "Lari"],
  ["GHS", 2, "Ghana Cedi"],
  ["GIP", 2, "Gibraltar Pound"],
  ["GMD", 2, "Dalasi"],
  ["GNF", 0, "Guinean Franc"],
  ["GTQ", 2, "Quetzal"],
  ["GYD", 2, "Guyana Dollar"],
  ["HKD", 2, "Hong Kong Dollar"],
  ["HNL", 2, "Lempira"],
  ["HTG", 2, "Gourde"],
  ["HUF", 2, "Forint"],
  ["IDR", 2, "Rupiah"],
  ["ILS", 2, "New Israeli Sheqel"],
  ["INR", 2, "Indian Rupee"],
  ["IQD", 3, "Iraqi Dinar"],
  ["IRR", 2, "Iranian Rial"],
  ["ISK", 0, "Iceland Krona"],
  ["JMD", 2, "Jamaican Dollar"],
  ["JOD", 3, "Jordanian Dinar"],
  ["JPY", 0, "Yen"],
  ["KES", 2, "Kenyan Shilling"],
  ["KGS", 2, "Som"],
  ["KHR", 2, "Riel"],
  ["KMF", 0, "Comorian Franc"],
  ["KPW", 2, "North Korean Won"],
  ["KRW", 0, "Won"],
  ["KWD", 3, "Kuwaiti Dinar"],
  ["KYD", 2, "Cayman Islands Dollar"],
  ["KZT", 2, "Tenge"],
  ["LAK", 2, "Lao Kip"],
  ["LBP", 2, "Lebanese Pound"],
  ["LKR", 2, "Sri Lanka Rupee"],
  ["LRD", 2, "Liberian Dollar"],
  ["LSL", 2, "Loti"],
  ["LYD", 3, "Libyan Dinar"],
  ["MAD", 2, "Moroccan Dirham"],
  ["MDL", 2, "Moldovan Leu"],
  ["MGA", 2, "Malagasy Ariary"],
  ["MKD", 2, "Denar"],
  ["MMK", 2, "Kyat"],
  ["MNT", 2, "Tugrik"],
  ["MOP", 2, "Pataca"],
  ["MRU", 2, "Ouguiya"],
  ["MUR", 2, "Mauritius Rupee"],
  ["MVR", 2, "Rufiyaa"],
  ["MWK", 2, "Malawi Kwacha"],
  ["MXN", 2, "Mexican Peso"],
  ["MYR", 2, "Malaysian Ringgit"],
  ["MZN", 2, "Mozambique Metical"],
  ["NAD", 2, "Namibia Dollar"],
  ["NGN", 2, "Naira"],
  ["NIO", 2, "Cordoba Oro"],
  ["NOK", 2, "Norwegian Krone"],
  ["NPR", 2, "Nepalese Rupee"],
  ["NZD", 2, "New Zealand Dollar"],
  ["OMR", 3, "Rial Omani"],
  ["PAB", 2, "Balboa"],
  ["PEN", 2, "Sol"],
  ["PGK", 2, "Kina"],
  ["PHP", 2, "Philippine Peso"],
  ["PKR", 2, "Pakistan Rupee"],
  ["PLN", 2, "Zloty"],
  ["PYG", 0, "Guarani"],
  ["QAR", 2, "Qatari Rial"],
  ["RON", 2, "Romanian Leu"],
  ["RSD", 2, "Serbian Dinar"],
  ["RUB", 2, "Russian Ruble"],
  ["RWF", 0, "Rwanda Franc"],
  ["SAR", 2, "Saudi Riyal"],
  ["SBD", 2, "Solomon Islands Dollar"],
  ["SCR", 2, "Seychelles Rupee"],
  ["SDG", 2, "Sudanese Pound"],
  ["SEK", 2, "Swedish Krona"],
  ["SGD", 2, "Singapore Dollar"],
  ["SHP", 2, "Saint Helena Pound"],
  ["SLE", 2, "Leone"],
  ["SOS", 2, "Somali Shilling"],
  ["SRD", 2, "Surinam Dollar"],
  ["SSP", 2, "South Sudanese Pound"],
  ["STN", 2, "Dobra"],
  ["SVC", 2, "El Salvador Colon"],
  ["SYP", 2, "Syrian Pound"],
  ["SZL", 2, "Lilangeni"],
  ["THB", 2, "Baht"],
  ["TJS", 2, "Somoni"],
  ["TMT", 2, "Turkmenistan New Manat"],
  ["TND", 3, "Tunisian Dinar"],
  ["TOP", 2, "Pa’anga"],
  ["TRY", 2, "Turkish Lira"],
  ["TTD", 2, "Trinidad and Tobago Dollar"],
  ["TWD", 2, "New Taiwan Dollar"],
  ["TZS", 2, "Tanzanian Shilling"],
  ["UAH", 2, "Hryvnia"],
  ["UGX", 0, "Uganda Shilling"],
  ["USD", 2, "US Dollar"],
  ["UYU", 2, "Peso Uruguayo"],
  ["UZS", 2, "Uzbekistan Sum"],
  ["VED", 2, "Bolívar Soberano (digital)"],
  ["VES", 2, "Bolívar Soberano"],
  ["VND", 0, "Dong"],
  ["VUV", 0, "Vatu"],
  ["WST", 2, "Tala"],
  ["XAF", 0, "CFA Franc BEAC"],
  ["XCD", 2, "East Caribbean Dollar"],
  ["XCG", 2, "Caribbean Guilder"],
  ["XOF", 0, "CFA Franc BCEAO"],
  ["XPF", 0, "CFP Franc"],
  ["YER", 2, "Yemeni Rial"],
  ["ZAR", 2, "Rand"],
  ["ZMW", 2, "Zambian Kwacha"],
  ["ZWG", 2, "Zimbabwe Gold"],
];

/** Maintained ISO 4217 active fiat list (no metals, funds, or testing codes). Sorted by code. */
export const CURRENCIES: readonly CurrencyInfo[] = Object.freeze(
  TABLE.map(([code, exponent, name]) => Object.freeze({ code, exponent, name })),
);

const BY_CODE: ReadonlyMap<string, CurrencyInfo> = new Map(CURRENCIES.map((c) => [c.code, c]));

/** Exact (case-sensitive) ISO code lookup; undefined for unsupported codes. */
export function getCurrency(code: string): CurrencyInfo | undefined {
  return BY_CODE.get(code);
}

/** Common picks surfaced first in selectors. */
export const COMMON_CURRENCIES: readonly string[] = ["EUR", "USD", "GBP", "PLN", "CHF", "JPY"];
